# Generated by Django 4.2.7 on 2024-06-07 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_remove_event_role_remove_role_role_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 20, 12, 38, 644423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 20, 12, 38, 644402, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 20, 12, 38, 649074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 20, 12, 38, 648746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 20, 12, 38, 649424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 20, 12, 38, 649413, tzinfo=datetime.timezone.utc)),
        ),
    ]
