version: '3'

services:
  backend:
    # image: back:100
    build:
      context: ./event_management/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./event_management/:/app
      - /static/:/app/static
      - ./log/uwsgi/:/var/log/uwsgi/
      - ./log/event_management/:/var/log/event_management/
    ports:
      - "8000:8000"
    depends_on:
      - db

  # frontend:
  #   # image: front:100
  #   build:
  #     context: ../frontend  # Path to your React frontend directory
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ../frontend/src:/app/src
  #   depends_on:
  #     - backend

  db:
    container_name: postgres-service
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - ./db:/var/lib/postgresql/data




  